### ISSUE TITLE
[BOOK] - Elaboración del componente Button

### ISSUE THREAD

**Issue by D3Portillo** [nodeschoolsm/website#3]
**Notes/Feedback:**

Gracias por tu colaboración en para los componentes de UI en la comunidad. 
Los siguientes botones debe ser `fluid` y adaptar su ancho al contenedor. Además se necesita de 2 "sabores" del componente, estás libre de decidir cómo puede funcionar la lógica para la selección del "sabor", ten en cuenta que es necesario sí tener un sabor por defecto del componente.

**Que se espera pueda hacer el boton**

- Se podrá ajustar las clases pasandolas por la prop  `className`
- El nombre del componente es `Button` 

**Clases de tailwind en el componente**

`bg-yellow text-black font-black text-xl px-6 py-5`

**Recursos/Resources:**

![](https://cdn.discordapp.com/attachments/756482229009514507/757323042954281100/Button.svg)

## Todo

- [ ] Elaboración del "sabor" Primary del boton
- [ ] Elaboración del "sabor" Secundary del boton
- [ ] Test local importando el componente realizado
- [ ] Integrado a master
---

**[Información de TailwindCSS](https://github.com/nodeschoolsm/website/blob/master/docs/TailwindCSS.md)**

<sub>Remember you can suggest a better way of doing this, just spill the beans : )</sub>

**Comment by D3Portillo** [comment]
@x905 Gracias por colaborar en el desarrollo del componente, espero tu PR, tienes asignado el issue : )

**Comment by X905** [comment]
👨‍💻 me alegra poder colaborar!

**Comment by D3Portillo** [comment]
He movido la task a "in progress" , muchas gracias @X905  , espero tu PR :'3

**Comment by D3Portillo** [comment]
Por cierto, para los `:hover` puedes usar las clases de tailwind `shadow-yellow` y `shadow-grey`

**Comment by X905** [comment]
Hola he hecho un PR (#4 ) con el nuevo componente, me gustaría tener una crítica, no estoy seguro si esa manera es la correcta para los sabores, ya que al final he creado dos elementos (Button y ButtonGrey), se podría descartar ButtonGrey ya que Button puede recibir las clases para tener el segundo sabor.

**Comment by D3Portillo** [comment]
Hola @X905 , he dejado unos comentarios de cómo podría mejorar un poquin el PR #4  . Muchas gracias :heart:
