### ISSUE TITLE
[BOOK] - Desarrollo del componente Input

### ISSUE THREAD

**Issue by D3Portillo** [nodeschoolsm/website#5]
**Notes/Feedback:**

El objetivo es crear un componente de tipo Input que pueda usarse en Formularios, en sí, el componente puede ser Uncontrolled y Controlled, la prop que expondrá el componente para ser "controlable" es `onChange` y `value`

## Que se espera pueda hacer el Input

-  Se podrá ajustar las clases pasandolas por la prop className
-  El nombre del componente es **Input**

**Recursos/Resources:**

![Input](https://user-images.githubusercontent.com/26236985/94370251-2a5c5080-00ac-11eb-847e-333f48e855b4.png)

## Todo

- [x] Prototipo del componente
- [x] Elaboración de Sabores: (Dark, Light)
- [x] Agregar Jest tests
- [x] Visualizar el Storybook
- [x] Integrar a la master

---
Include any subtask you will be doing to complete this track task, so anyone reading this can contribute too, follow this examples:
- Refactor buggy code
- Update old JS library
- Includes Tailwindcss

<sub>Remember you can suggest a better way of doing this, just spill the beans : )</sub>

**Comment by D3Portillo** [comment]
Tomaré el desarrollo de este componente : )
