### ISSUE TITLE
[BOOK] - Marquee

### ISSUE THREAD

**Issue by D3Portillo** [nodeschoolsm/website#7]
**Notes/Feedback:**

La idea es crear un componente marquee que se adapte a su contenedor padre y que haga la animación de desplazar texto cómo lo hacen las marquees, sería muy genial si la marquee no muestre espacios en blanco y el texto que se busque mostrar en ella sea animado continuamente.

**Recursos/Resources:**

![marquee](https://user-images.githubusercontent.com/26236985/97250244-2d418280-17cb-11eb-967a-dd4d1b674634.png)

Sería genial si pudiera imitarse cúalquiera de estos ejemplos:
- https://codepen.io/cyboc23/pen/NWqYyzx
- https://codepen.io/Punkrazio/details/QWbYvBv

Puedes usar cúalquiera estás clases de tailwind, `bg-yellow font-black font-poppins`. [Ver configuración completa de Tailwind](https://github.com/nodeschoolsm/website/blob/master/tailwind.config.js)

## Todo

- [ ] Crear el component Marquee
- [ ] El componente se llama Marquee
- [ ] El componente Marquee acepta cómo children el contenido a ser animado

**Comment by ElvisGmz** [comment]
Yo me sueno el marquee

**Comment by D3Portillo** [comment]
Gracias @ElvisGmz :3

**Comment by D3Portillo** [comment]
cúalquier duda acá estamos : ' )
