### ISSUE TITLE
[BOOK] - Footer

### ISSUE THREAD

**Issue by D3Portillo** [nodeschoolsm/website#8]
## Sobre el issue

Gracias por el interés de colaborar en el desarrollo del website. Para esta ocación se necesita elaborar el componente Footer del website y blog. Debe acoplarse a su contenedor, puedes usar la clase `w-full`.

### Resultado esperado

![footer](https://user-images.githubusercontent.com/26236985/97251444-84e0ed80-17cd-11eb-9ad4-a5078a1482a6.png)

PD: Ignora los bordes de color rojo, sirve para saber que el botón de la derecha es de fondo blanco

## Assets

![OKC](https://user-images.githubusercontent.com/26236985/97251449-87434780-17cd-11eb-8fd4-c63a6639da11.png)
![OKCBanner](https://user-images.githubusercontent.com/26236985/97251455-89a5a180-17cd-11eb-9181-0fd09b2c170c.png)

Para el icono se recomienda usar un icono de su preferencia disponible en <https://react-icons.github.io/react-icons>. Buscar palabra clave `arrowup`

## Todo

- [ ] Elaboración del componente
- [ ] El Footer incluye los assets e iconos listados en el issue
- [ ] El componente se llama `Footer`

---
Un poco de info dev, https://github.com/nodeschoolsm/website/tree/master/docs
